// Feature 9 — shared helper for streaming generated bytes as a download.
//
// TS 5.7+ types Uint8Array as Uint8Array<ArrayBufferLike>, which does not satisfy
// BodyInit/BlobPart (these want a concrete ArrayBuffer). Copying into a fresh
// ArrayBuffer sidesteps the variance friction with no meaningful runtime cost.
export function fileResponse(bytes: Uint8Array, contentType: string, filename: string): Response {
  const ab = new ArrayBuffer(bytes.byteLength)
  new Uint8Array(ab).set(bytes)
  return new Response(ab, {
    status: 200,
    headers: {
      'Content-Type': contentType,
      'Content-Disposition': `attachment; filename="${filename}"`,
      'Cache-Control': 'no-store',
    },
  })
}
