// AUTO-GENERATED by _gen_templates.mjs from the Dr ABIBOU BA reference models
// (reference/source/TYPE NORMAL ECHO DR BA.docx + MODELES CR SCAN TYPE NORMAL DR BA.docx).
// Do not edit by hand — re-run the generator to refresh. F16 starter library.
//
// These are NORMAL report models a clinic admin can install into their own
// clinic. They carry the four HPD sections; the doctor's signature line has been
// stripped. Special table layouts (Scannopelvimétrie, TAGT) are excluded here and
// handled by F18.

import type { ExamModality } from '@/types/exam'

export interface StarterTemplate {
  title: string
  examType: string
  modality: ExamModality
  indication: string
  technique: string
  /** RÉSULTATS → report_templates.findings_template */
  findings: string
  /** CONCLUSION → report_templates.impression_template */
  impression: string
}

export const STARTER_LIBRARY_AUTHOR = 'Dr ABIBOU BA'
export const STARTER_LIBRARY_SOURCE = 'seed:dr-ba'

export const STARTER_TEMPLATES: StarterTemplate[] = [
  {
    title: "ECHOGRAPHIE ABDOMINALE (variante 1)",
    examType: "echographie_abdominale_variante_1",
    modality: "US",
    indication: "",
    technique: "",
    findings: "Foie : De taille normale (flèche hépatique à … mm), aux contours réguliers, homogène sans lésion focale suspecte.\nLe tronc porte est perméable, de calibre normal avec un flux physiologique.\nLa vésicule biliaire a une paroi fine, elle est alithiasique, non douloureuse sous la sonde.\nLes voies biliaires intra et extra-hépatiques ne sont pas dilatées.\nPancréas : De taille et d’échostructure normales.\nRate : De taille normale (… mm) d’échostructure homogène.\nReins : De taille normale et symétrique mesurant …. mm à droite et …. mm à gauche.\nBonne différenciation parenchymo-sinusale.\nLes cavités pyélocalicielles ne sont pas dilatées.\nRétro- péritoine : il n’y a pas d’image anormale du rétro-péritoine médian.\nOn ne met pas en évidence d’épanchement intra-péritonéal.\nPas d’adénomégalie profonde.",
    impression: "Examen normal ce jour",
  },
  {
    title: "ECHOGRAPHIE ABDOMINALE (variante 2)",
    examType: "echographie_abdominale_variante_2",
    modality: "US",
    indication: "Surveillance d’une hépatite chronique virale B.",
    technique: "",
    findings: "Foie de taille normale mesuré à …. mm, non dysmorphique, aux contours réguliers, d’échostructure homogène sans lésion focale.\nAbsence d’anomalie vésiculo-biliaire.\nTronc porte perméable, de calibre normal mesuré à ….. mm avec un flux physiologique circulant à une vitesse de ….. cm/s.\nAbsence de voie de dérivation porto-systémique.\nRate de taille normale d’échostructure homogène mesurée à …mm.\nIntégrité morphologique des reins et du pancréas.\nPas d’épanchement dans le péritoine.\nPas d’adénomégalie.",
    impression: "Foie non dysmorphique sans lésion focale suspecte.\nAbsence de signe d’hypertension portale",
  },
  {
    title: "ECHOGRAPHIE ABDOMINO-PELVIENNE",
    examType: "echographie_abdomino_pelvienne",
    modality: "US",
    indication: "",
    technique: "",
    findings: "ABDOMEN :\nFoie : De taille normale (flèche hépatique à … mm), aux contours réguliers, homogène sans lésion focale suspecte.\nLe tronc porte est perméable, de calibre normal avec un flux physiologique.\nLa vésicule biliaire a une paroi fine, elle est alithiasique, non douloureuse sous la sonde.\nLes voies biliaires intra et extra-hépatiques ne sont pas dilatées.\nPancréas : De taille et d’échostructure normales.\nRate : De taille normale (… mm) d’échostructure homogène.\nReins : De taille normale et symétrique mesurant …. mm à droite et …. mm à gauche.\nBonne différenciation parenchymo-sinusale.\nLes cavités pyélocalicielles ne sont pas dilatées.\nRétro- péritoine : il n’y a pas d’image anormale du rétro-péritoine médian.\nOn ne met pas en évidence d’épanchement intra-péritonéal.\nPas d’adénomégalie profonde.\nPELVIS : (FEMME)\nExamen réalisé par voie sus pubienne et endo vaginale.\nUtérus antéversé antéfléchi, de taille normale mesurant … x …. x … mm, d’échostructure homogène sans lésion focale suspecte.\nEndomètre fin mesuré à …. mm.\nOvaires visualisés, de taille et d’échostructure normales.\nAbsence de masse annexielle objectivée.\nPas d’épanchement dans le Douglas",
    impression: "Examen normal ce jour.",
  },
  {
    title: "ECHOGRAPHIE DES VOIES URINAIRES",
    examType: "echographie_des_voies_urinaires",
    modality: "US",
    indication: "",
    technique: "",
    findings: "Reins de taille normale symétriques mesurant …. mm à droite et …. mm à gauche, aux contours réguliers avec une bonne différenciation parenchymo-sinusale, sans dilatation pyélo calicielle ni calcul visualisé.\nVessie en bonne réplétion à contenu transsonore alithiasique à paroi fine et régulière.\nRPM non significatif.\nProstate de taille normale mesurant …. x ….. x ….. mm soit un volume de … ml.",
    impression: "Echographie de l’arbre urinaire normal ce jour",
  },
  {
    title: "ECHOGRAPHIE OBSTETRICALE",
    examType: "echographie_obstetricale",
    modality: "US",
    indication: "Bilan de grossesse T2/T3.",
    technique: "",
    findings: "Grossesse mono-fœtale intra utérine évolutive\nVitalité : mouvements actifs fœtaux présents avec fréquence cardiaque à … bpm.\nBiométrie : PA= …… mm ; LF= …. mm ; PC = …. mm ; BIP =…. mm soit un âge gestationnel de … SA +/- …. j.\nPoids estimé à …. g.\nMorphologie :\nPôle céphalique normale ; Rachis régulier ; Cœur quatre cavités ; extrémité quatre membres.\nPrésentation : céphalique dos à …...\nPlacenta …………. grade …. non bas inséré, sans signe de décollement.\nLiquide en quantité suffisante.\nCordon ombilical à trois vaisseaux deux artères et une veine.",
    impression: "Grossesse mono-fœtale intra utérine évolutive avec bien être fœtal correspondant à un âge gestationnel de ….SA +/- …j.\nDAP : vers le …/…/.2026.",
  },
  {
    title: "ECHOGRAPHIE OBSTETRICALE (T1)",
    examType: "echographie_obstetricale_t1",
    modality: "US",
    indication: "",
    technique: "",
    findings: "Grossesse mono-fœtale intra utérine, corporéal, évolutive, avec une fréquence cardiaque à … bpm\nBiométrie : LCC mesurée à …. mm soit un âge gestationnel de …SA ….j +/- .\nPlacenta ………., bien inséré, sans signe de décollement.\nPas d’épanchement dans le Douglas.\nPas d’anomalie utéro-annexielle.\nReins en position modale.\nLiquide amniotique en quantité suffisante.",
    impression: "Grossesse mono-fœtale intra utérine évolutive correspondant à un âge gestationnel de …SA ….j +/- .\nDAP : vers le …/…/.2026.",
  },
  {
    title: "ECHOGRAPHIE DES BOURSES",
    examType: "echographie_des_bourses",
    modality: "US",
    indication: "",
    technique: "",
    findings: "Bourse droite :\nTestis de taille normale mesurant … x …. x …. mm soit un volume de … ml, d’échostructure homogène, avec une vascularisation normale.\nEpididyme de taille et d’échostructure normale.\nEnveloppes fines.\nVaginale : pas d’épanchement\nRéseau pampiniforme : absence de reflux lors de la manœuvre de Valsalva\nBourse gauche :\nTestis de taille normale mesurant … x …. x …. mm soit un volume de … ml, d’échostructure homogène, avec une vascularisation normale.\nEpididyme de taille et d’échostructure normale.\nEnveloppes fines.\nVaginale : pas d’épanchement\nRéseau pampiniforme : absence de reflux lors de la manœuvre de Valsalva",
    impression: "Examen normal ce jour.",
  },
  {
    title: "ECHOGRAPHIE PELVIENNE (FEMME)",
    examType: "echographie_pelvienne_femme",
    modality: "US",
    indication: "",
    technique: "",
    findings: "Examen réalisé par voie sus pubienne et endo vaginale.\nUtérus antéversé antéfléchi, de taille normale mesurant … x …. x … mm, d’échostructure homogène sans lésion focale suspecte.\nEndomètre fin mesuré à …. mm.\nOvaires visualisés, de taille et d’échostructure normales.\nAbsence de masse annexielle objectivée.\nPas d’épanchement dans le Douglas",
    impression: "Examen normal ce jour.",
  },
  {
    title: "ECHOGRAPHIE DOPPLER TSA",
    examType: "echographie_doppler_tsa",
    modality: "US",
    indication: "recherche étiologique AVC ischémique",
    technique: "",
    findings: "Epaisseur intimo-médiale normale à droite comme à gauche\nBonne perméabilité des artères carotides communes, externes et internes.\nPas de plaque athéromateuse objectivée.\nLes bulbes carotidiens sont libres.\nBonne perméabilité des artères vertébrales avec une codominance, sans anomalie pariétale ou de calibre.\nPas de dissection artérielle décelée.\nLes vitesses et index de résistance sont normaux.",
    impression: "Echodoppler des TSA normale ce jour",
  },
  {
    title: "SCANNER CEREBRAL (sans injection)",
    examType: "scanner_cerebral_sans_injection",
    modality: "CT",
    indication: "",
    technique: "acquisition hélicoïdale sans injection de contraste. DLP= …… mGy/cm",
    findings: "Absence d’anomalie de densité du parenchyme ou de collection péri cérébrale.\nStructures médianes en place.\nPas de dilatation du système ventriculaire.\nAspect normal des espaces sous arachnoïdiens ou des citernes\nCharnière cervico-occipitale normale.",
    impression: "Scanner cérébral normal.",
  },
  {
    title: "SCANNER CEREBRAL (avec injection)",
    examType: "scanner_cerebral_avec_injection",
    modality: "CT",
    indication: "",
    technique: "acquisition hélicoïdale sans et avec injection de contraste. DLP= mGy/cm",
    findings: "Absence d’anomalie de densité du parenchyme ou de collection péri cérébrale.\nStructures médianes en place.\nPas de dilatation du système ventriculaire.\nAspect normal des espaces sous arachnoïdiens ou des citernes\nBonne perméabilité du polygone de Willis et des sinus veineux\nCharnière cervico-occipitale normale.",
    impression: "Scanner cérébral normal.",
  },
  {
    title: "ANGIOSCANNER THORAX",
    examType: "angioscanner_thorax",
    modality: "CT",
    indication: "",
    technique: "acquisition hélicoïdale avec injection de contraste. DLP= ….mGy/cm",
    findings: "Absence de foyer parenchymateux ou de nodule ou micronodule pulmonaire.\nPas d'adénomégalie médiastinale, hilaire, axillaire ou sous claviculaire.\nAspect normal de l’arbre trachéo-bronchique.\nPas d'épanchement pleural ou péricardique.\nBonne perméabilité du cœur et des gros vaisseaux.\nPas de lésion focale osseuse suspecte",
    impression: "TDM thoracique normale",
  },
  {
    title: "SCANNER THORAX",
    examType: "scanner_thorax",
    modality: "CT",
    indication: "",
    technique: "acquisition hélicoïdale sans injection de contraste. DLP= ….mGy/cm",
    findings: "Absence de foyer parenchymateux ou de nodule ou micronodule pulmonaire.\nPas d'adénomégalie médiastinale, hilaire, axillaire ou sous claviculaire visible (sous réserve d’un examen non injecté)\nAspect normal de l’arbre trachéo-bronchique.\nPas d'épanchement pleural ou péricardique.\nPas de lésion focale osseuse suspecte",
    impression: "TDM thoracique normale",
  },
  {
    title: "SCANNER ABDOMINAL",
    examType: "scanner_abdominal",
    modality: "CT",
    indication: "",
    technique: "acquisition hélicoïdale avec injection de contraste. DLP = ……. mGy/cm",
    findings: "Foie de taille normale, non dysmorphique, aux contours réguliers, avec un rehaussement homogène après injection de produit de contraste.\nPas d’anomalie des voies biliaires ou de la vésicule.\nTronc porte perméable de calibre normal.\nAspect normal du pancréas, de la rate, des reins et des surrénales.\nAbsence d’épanchement ou d’épaississement péritonéal.\nPas d’anomalie pariétale digestive notée.\nPas d’adénomégalie profonde.\nAspect normal des voies excrétrices urinaires\nBonne perméabilité des gros vaisseaux.\nPas de lésion focale osseuse suspecte.",
    impression: "Scanner abdominal normal.",
  },
  {
    title: "SCANNER ABDOMINO-PELVIEN",
    examType: "scanner_abdomino_pelvien",
    modality: "CT",
    indication: "",
    technique: "acquisition hélicoïdale avec injection de contraste. DLP = ……. mGy/cm",
    findings: "Foie de taille normale, non dysmorphique, aux contours réguliers, avec un rehaussement homogène après injection de produit de contraste.\nPas d’anomalie des voies biliaires ou de la vésicule.\nTronc porte perméable de calibre normal.\nAspect normal du pancréas, de la rate, des reins et des surrénales.\nAbsence d’épanchement ou d’épaississement péritonéal.\nPas d’anomalie pariétale digestive notée.\nPas d’adénomégalie profonde.\nAspect normal des voies excrétrices urinaires\nBonne perméabilité des gros vaisseaux.\nPas de lésion focale osseuse suspecte.",
    impression: "Scanner abdominal normal.",
  },
  {
    title: "SCANNER DU RACHIS LOMBAIRE",
    examType: "scanner_du_rachis_lombaire",
    modality: "CT",
    indication: "",
    technique: "acquisition volumique sans injection. DLP= ….mGy/cm",
    findings: "Minéralisation osseuse satisfaisante.\nAbsence d’anomalie transitionnelle ou d’étroitesse canalaire constitutionnelle.\nRespect de la hauteur des corps vertébraux avec un bon alignement du mur postérieur.\nAbsence de lyse isthmique.\nAspect normal des articulaires postérieures et des articulations sacro-iliaques\nEn L3-L4 : aspect normal du disque et des émergences radiculaires\nEn L4-L5 : aspect normal du disque et des émergences radiculaires\nEn L5-S1 : aspect normal du disque et des émergences radiculaires\nAspect normal des parties molles péri-vertébrales.",
    impression: "Scanner du rachis lombaire normal.",
  },
  {
    title: "ANGIOSCANNER DES TRONCS SUPRA-AORTIQUES",
    examType: "angioscanner_des_troncs_supra_aortiques",
    modality: "CT",
    indication: "",
    technique: "acquisition hélicoïdale avec injection de contraste. DLP =…..mGy/cm",
    findings: "Crosse de l’aorte de calibre normal.\nNaissance modale des troncs supra aortiques.\nBonne perméabilité des carotides communes, internes et externes, sans anomalie pariétale.\nAspect normal des bulbes carotidiens.\nPerméabilité des artères vertébrales avec codominance, participant toutes les deux à la naissance du tronc basilaire qui est aussi perméable\nLe polygone de Willis est complet.\nAspect normal des Sinus veineux.",
    impression: "Angioscanner des TSA normal.",
  },
  {
    title: "SCANNER THORACO-ABDOMINO-PELVIEN",
    examType: "scanner_thoraco_abdomino_pelvien",
    modality: "CT",
    indication: "",
    technique: "acquisition hélicoïdale avec injection de contraste. DLP= …. mGy/cm",
    findings: "Etage thoracique :\nPas de lésion parenchymateuse ou de nodule ou micronodule pulmonaire.\nAbsence d'adénomégalie médiastinale, hilaire, axillaire ou sous claviculaire.\nAspect normal de l’arbre trachéo-bronchique.\nPas d'épanchement pleural ou péricardique.\nBonne perméabilité du cœur et des gros vaisseaux.\nEtage abdominal :\nFoie de taille normale, non dysmorphique, aux contours réguliers, avec un rehaussement homogène après injection de produit de contraste.\nPas d’anomalie des voies biliaires ou de la vésicule.\nTronc porte perméable de calibre normal.\nAspect normal du pancréas, de la rate, des reins et des surrénales.\nAbsence d’épanchement ou d’épaississement péritonéal.\nPas d’anomalie pariétale digestive notée.\nPas d’adénomégalie profonde.\nAspect normal des voies excrétrices urinaires\nBonne perméabilité des gros vaisseaux.\nSquelette axial :\nAbsence de lésion focale osseuse suspecte.",
    impression: "Scanner thoraco-abdominopelvien normal.",
  },
  {
    title: "SCANNER DU RACHIS CERVICAL",
    examType: "scanner_du_rachis_cervical",
    modality: "CT",
    indication: "",
    technique: "acquisition volumique sans injection de contraste. DLP= …. mGy/cm",
    findings: "Minéralisation osseuse satisfaisante.\nRespect de la hauteur des corps vertébraux avec bon alignement du mur postérieur.\nAspect normal des articulaires postérieures.\nAspect normal des processus unciformes.\nAspect normal du disque à tous les étages.\nAspect normal des parties molles péri-vertébrales.",
    impression: "Scanner rachis cervical normal.",
  },
  {
    title: "SCANNER DES ROCHERS",
    examType: "scanner_des_rochers",
    modality: "CT",
    indication: "",
    technique: "acquisition volumique sur les rochers et reconstructions selon les plans d’intérêt.",
    findings: "Oreille externe et oreille moyenne ( à droite comme à gauche) :\nAspect normal du conduit auditif externe.\nAération normale des cavités tympano-mastoïdiennes.\nAbsence de déhiscence du canal semi-circulaire supérieur.\nIntégrité de la chaine ossiculaire.\nAspect normal de la fissula antefenestram\nAspect normal des fenêtres ronde et ovale.\nPosition normale du canal facial, sans signe de lyse ou de fracture.\nPas de procidence du canal carotidien, du golfe de la jugulaire ou du sinus sigmoïde.\nOreille interne (à droite comme à gauche):\nMorphologie normale de la cochlée avec un modiulus présent.\nLe canal cochléaire est de calibre normal à droite comme à gauche.\nAspect normal du vestibule.\nAbsence de dilatation de l’aqueduc du vestibule.\nPas d’anomalie du conduit auditif interne.",
    impression: "Scanner des rochers normal.",
  },
  {
    title: "SCANNER DES SINUS DE LA FACE",
    examType: "scanner_des_sinus_de_la_face",
    modality: "CT",
    indication: "",
    technique: "acquisition volumique sur les zones d’intérêt sans injection de produit de contraste. DLP= ….. mGy/cm",
    findings: "Bonne aération des cavités naso-sinusiennes.\nLes ostiums des sinus maxillaires et le canal naso frontal sont libres.\nPas d’anomalie structurelle de la filière nasale.\nPas de déviation de cloison significative.\nAbsence d’anomalie de rapport de la cuvette des sinus avec les apex dentaires.\nPas de variante anatomique significative.",
    impression: "Scanner des sinus normal",
  },
]
