-- =============================================================================
-- Radiora Medical — Phase 4B Patient Explanations
-- =============================================================================
-- Prerequisite: 006_ai_workflow_foundation.sql must already be applied.
-- All statements are idempotent and safe to re-run.
-- No external AI calls — explanations generated by local engine only.
-- =============================================================================

-- ── patient_explanations ──────────────────────────────────────────────────────
-- Stores plain-language patient explanations derived from finalized reports.
-- Always separate from the clinical report — never modifies the original.

create table if not exists public.patient_explanations (
  id                      uuid        primary key default gen_random_uuid(),
  clinic_id               uuid        references public.clinics(id) on delete cascade,
  report_id               uuid        not null references public.reports(id) on delete cascade,
  patient_id              uuid        not null references public.patients(id) on delete cascade,
  study_id                uuid        not null references public.studies(id) on delete cascade,
  language                text        not null default 'en',
  status                  text        not null default 'draft'
                                      check (status in ('draft', 'approved', 'rejected', 'archived')),
  source_report_version_id uuid       references public.report_versions(id) on delete set null,
  explanation_text        text        not null,
  disclaimer              text        not null,
  created_by              uuid        references auth.users(id) on delete set null,
  approved_by             uuid        references auth.users(id) on delete set null,
  approved_at             timestamptz,
  rejected_by             uuid        references auth.users(id) on delete set null,
  rejected_at             timestamptz,
  rejection_reason        text,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

-- ── Indexes ───────────────────────────────────────────────────────────────────

create index if not exists patient_explanations_report_id_idx   on public.patient_explanations (report_id);
create index if not exists patient_explanations_clinic_id_idx   on public.patient_explanations (clinic_id);
create index if not exists patient_explanations_patient_id_idx  on public.patient_explanations (patient_id);
create index if not exists patient_explanations_status_idx      on public.patient_explanations (status);

-- ── updated_at trigger ────────────────────────────────────────────────────────

drop trigger if exists patient_explanations_updated_at on public.patient_explanations;

create trigger patient_explanations_updated_at
  before update on public.patient_explanations
  for each row execute function public.handle_updated_at();

-- ── RLS ───────────────────────────────────────────────────────────────────────

alter table public.patient_explanations enable row level security;

-- select: clinic_admin + radiologist can see all explanations within their clinic.
-- Technicians and viewers have no access — patient explanations are medical-staff only.
drop policy if exists "patient_explanations: select" on public.patient_explanations;
create policy "patient_explanations: select"
  on public.patient_explanations for select to authenticated
  using (
    (
      clinic_id = public.get_current_user_clinic_id()
      and public.get_current_user_role() in ('clinic_admin', 'radiologist', 'super_admin')
    )
    or public.is_super_admin()
  );

-- insert: clinic_admin + radiologist only
drop policy if exists "patient_explanations: insert" on public.patient_explanations;
create policy "patient_explanations: insert"
  on public.patient_explanations for insert to authenticated
  with check (
    (
      clinic_id = public.get_current_user_clinic_id()
      and public.get_current_user_role() in ('clinic_admin', 'radiologist', 'super_admin')
    )
    or public.is_super_admin()
  );

-- update: clinic_admin + radiologist can approve/reject/archive
drop policy if exists "patient_explanations: update" on public.patient_explanations;
create policy "patient_explanations: update"
  on public.patient_explanations for update to authenticated
  using (
    (
      clinic_id = public.get_current_user_clinic_id()
      and public.get_current_user_role() in ('clinic_admin', 'radiologist', 'super_admin')
    )
    or public.is_super_admin()
  );
